### ISSUE TITLE
Is this supposed to work with python 3.10

### ISSUE THREAD

**Issue by goofyseeker311** [expertsleepersltd/sf2_to_dex#4]
all print statements complain about missing parentheses.
chunk.py raises runtimerror at line 65 chuck.skip().
did you ever test this for generic .sf2 files (that work with vlc).

**Comment by expertsleepers** [comment]
Python 3 version is: https://github.com/expertsleepersltd/sf2_to_dex/blob/master/sf2dex3py.py

If you have a file you'd like us to test, send it over or attach it here.

**Comment by goofyseeker311** [comment]
search for just_t4.rar (about 300MB, .sf2 about 526MB unpacked) on internet, (some tyros 4 soundfont)

Windows console output (justt4.sf2 renamed to no-space):

Reading soundfont:  justt4.sf2
Traceback (most recent call last):
  File "C:\Users\xxxxx\Downloads\sf2_to_dex-master\sf2dex3py.py", line 181, in <module>
    main()
  File "C:\Users\xxxxx\Downloads\sf2_to_dex-master\sf2dex3py.py", line 177, in main
    readSoundfont()
  File "C:\Users\xxxxx\Downloads\sf2_to_dex-master\sf2dex3py.py", line 79, in readSoundfont
    chunk.skip()
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python310\lib\chunk.py", line 160, in skip
    self.file.seek(n, 1)
  File "C:\Users\xxxxx\AppData\Local\Programs\Python\Python310\lib\chunk.py", line 113, in seek
    raise RuntimeError
RuntimeError

I think you might have a file size memory load issue because of the large file size.

**Comment by expertsleepers** [comment]
Please post a link to the file so I know we're looking at exactly the same thing.
